### PR TITLE
Add TheoX's name on Challenge.md

### PR DESCRIPTION
**Pull request by xenakistheo**

### CODE REVIEW

**Review by Northo — APPROVED** [review]
Nicely done! Feel free to merge:)

**Comment by Northo** [comment]
In order to mege, click 'Merge pull request'. That will also mark the PR as closed ;)

**Comment by xenakistheo** [comment]
It says "Only those with write access to this repository can merge pull requests". I can't seem to find the 'Merge pull request' :(

**Comment by Northo** [comment]
See if WebSjef may give you write permissions.

**Pull request merged**
